language: python

os:
  - linux

dist: bionic

python:
  - "3.7"

install:
  - pip install pytest codecov pytest-cov
  - python setup.py install

script:
  - pytest --cov src --cov-report term-missing tests/test_one.py

after_success:
  - codecov -cF one
