language: python

os:
  - linux

dist: bionic

python:
  - "3.7"

install:
  - pip install pytest codecov pytest-cov

script:
  - pytest --cov src --cov-report term-missing tests/test_one.py
  - codecov -cF one

