version: 2.1

# -------------------------------------------------------------------------------------
# Jobs to run
# -------------------------------------------------------------------------------------
jobs:

  test_three:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Run test three
          command: |
            pip install pytest pytest-cov
            pytest --cov src --cov-report term-missing tests/test_three.py
      - run:
          name: Codecov upload
          command: |
            bash <(curl -s https://codecov.io/bash) -Z -F three

# -------------------------------------------------------------------------------------
# Workflows
# -------------------------------------------------------------------------------------
workflows:
  version: 2
  tests:
    jobs:
      - test_three
