version: 2.1

# -------------------------------------------------------------------------------------
# Jobs to run
# -------------------------------------------------------------------------------------
jobs:

  test_three:
    steps:
      - checkout
      - run:
          name: Run test three
          command: |
            pip install pytest codecov pytest-cov
            pytest --cov src --cov-report term-missing tests/test_three.py
            codecov -F three

# -------------------------------------------------------------------------------------
# Workflows
# -------------------------------------------------------------------------------------
workflows:
  version: 2
  tests:
    jobs:
      - test_three
