on: [pull_request, push]

jobs:
  mkl-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Run test two
      run: |
        pip install pytest codecov pytest-cov
        pytest --cov src --cov-report=xml tests/test_two.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: one
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
