on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            env:
              MYVAR: "got_it"

    steps:
    - uses: actions/checkout@v2
    - name: Setup Miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        miniconda-version: "latest"
        python-version: 3.7

    - name: Check conda and install dependencies
      shell: bash -l {0}
      run: |
        conda --version
        echo "MYVAR=${MYVAR}"
